config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

from pastry_shop.blog.views import MainPageView

urlpatterns = [
    path("", MainPageView.as_view(), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("pastry_shop.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("blog/", include("pastry_shop.blog.urls", namespace="blog")),
    path("shop/", include("pastry_shop.shop.urls", namespace="shop")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

pastry_shop/blog/urls.py
from django.urls import path

from pastry_shop.blog.views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostEditView,
    PostDeleteView,
    CommentEditView,
    CommentDeleteView,
)

app_name = "blog"

urlpatterns = [
    path("posts/", PostListView.as_view(), name="post-list"),
    path("posts/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("posts/add/", PostCreateView.as_view(), name="post-create"),
    path("posts/<int:pk>/edit/", PostEditView.as_view(), name="post-edit"),
    path("posts/<int:pk>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path("comments/<int:pk>/edit/", CommentEditView.as_view(), name="comment-edit"),
    path(
        "comments/<int:pk>/delete/", CommentDeleteView.as_view(), name="comment-delete"
    ),
]

pastry_shop/shop/urls.py
from django.urls import path

from pastry_shop.shop.views import (
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductEditView,
    ProductDeleteView,
    CategoryListView,
    CategoryDetailView,
    CategoryCreateView,
    CategoryEditView,
    CategoryDeleteView,
    ShopListView,
    ShopDetailView,
    ShopCreateView,
    ShopEditView,
    ShopDeleteView,
    CartDetailView,
    CartProductDeleteView,
    OrderListView,
    OrderDetailView,
    ShopProductAddView,
    ShopProductDeleteView,
)

app_name = "shop"

urlpatterns = [
    path("products/", ProductListView.as_view(), name="product-list"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product-detail"),
    path("products/add/", ProductCreateView.as_view(), name="product-create"),
    path("products/<int:pk>/edit/", ProductEditView.as_view(), name="product-edit"),
    path(
        "products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product-delete"
    ),
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path(
        "category/<slug:slug>/products",
        CategoryDetailView.as_view(),
        name="category-detail",
    ),
    path("category/add", CategoryCreateView.as_view(), name="category-create"),
    path("category/<slug:slug>/edit", CategoryEditView.as_view(), name="category-edit"),
    path(
        "category/<slug:slug>/delete",
        CategoryDeleteView.as_view(),
        name="category-delete",
    ),
    path("shops/", ShopListView.as_view(), name="shop-list"),
    path("shop/<int:pk>/", ShopDetailView.as_view(), name="shop-detail"),
    path("shop/add/", ShopCreateView.as_view(), name="shop-create"),
    path("shop/<int:pk>/edit/", ShopEditView.as_view(), name="shop-edit"),
    path("shop/<int:pk>/delete/", ShopDeleteView.as_view(), name="shop-delete"),
    path(
        "shop/<int:pk>/product/add/",
        ShopProductAddView.as_view(),
        name="shop-product-add",
    ),
    path(
        "shop/<int:pk>/product/<int:product_id>/",
        ShopProductDeleteView.as_view(),
        name="shop-product-remove",
    ),
    path("cart/", CartDetailView.as_view(), name="cart-detail"),
    path(
        "cart/product/<int:pk>/delete/",
        CartProductDeleteView.as_view(),
        name="cart-product-delete",
    ),
    path("orders/", OrderListView.as_view(), name="order-list"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
]

pastry_shop/users/urls.py
from django.urls import path

from pastry_shop.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

pastry_shop/blog/models.py
from django.db import models

# Create your models here.
from django.utils.translation import gettext_lazy as _

from pastry_shop.users.models import User


class Post(models.Model):
    title = models.CharField(_("Title"), max_length=64)
    content = models.TextField(_("Content"))
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return self.title


class Comment(models.Model):
    content = models.TextField(_("Content"))
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    post = models.ForeignKey("Post", on_delete=models.CASCADE, related_name="comments")

    def __str__(self):
        return f"{self.content[:20]} - {self.author.username}"

pastry_shop/shop/models.py
from autoslug import AutoSlugField
from django.db import models

# Create your models here.
from django.utils.translation import gettext_lazy as _

from pastry_shop.users.models import User


class Category(models.Model):
    name = models.CharField(_("Name"), max_length=100)
    slug = AutoSlugField(populate_from="name", unique=True, always_update=True)

    class Meta:
        verbose_name_plural = "Categories"
        ordering = ("name",)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(_("Name"), max_length=100)
    description = models.TextField(_("Description"))
    price = models.DecimalField(_("Price"), max_digits=7, decimal_places=2)
    amount = models.IntegerField(_("Amount"))
    categories = models.ManyToManyField(Category)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


class Cart(models.Model):
    client = models.OneToOneField(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through="ProductCart")

    def get_total(self):
        total = 0
        for product in self.productcart_set.all():
            total += product.get_price()
        return total

    def __str__(self):
        return f"{self.client.username}'s cart({self.pk})"


class ProductCart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    amount = models.IntegerField()

    def get_price(self):
        return self.amount * self.product.price


class Order(models.Model):
    class Status(models.IntegerChoices):
        PENDING = 1, _("Pending")
        READY = 2, _("Ready for pickup")
        PAID = 3, _("Paid")
        DELIVERED = 4, _("Delivered")

    client = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through="ProductOrder")
    status = models.IntegerField(choices=Status.choices, default=Status.PENDING)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.client.username}'s order({self.pk})"

    def get_total(self):
        total = 0
        for product in self.productorder_set.all():
            total += product.get_price()
        return total


class ProductOrder(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    amount = models.IntegerField()

    def get_price(self):
        return self.amount * self.product.price


class Shop(models.Model):
    name = models.CharField(_("Name"), max_length=100)
    city = models.CharField(_("City"), max_length=100)
    street = models.CharField(_("Street"), max_length=100)
    products = models.ManyToManyField(Product, through="Availability")

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


class Availability(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    amount = models.IntegerField()

pastry_shop/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for Pastry Shop."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

pastry_shop/blog/forms.py
from django import forms

from pastry_shop.blog.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "content")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)

pastry_shop/shop/forms.py
from django import forms

from pastry_shop.shop.models import Product, ProductCart


class ProductForm(forms.ModelForm):
    amount = forms.IntegerField(min_value=1)
    price = forms.DecimalField(min_value=0.01, max_digits=7, decimal_places=2)

    class Meta:
        model = Product
        fields = "__all__"
        widgets = {"categories": forms.CheckboxSelectMultiple}


class CartProductAddForm(forms.Form):
    amount = forms.IntegerField(min_value=1)


class ShopProductAddForm(forms.Form):
    product = forms.ModelChoiceField(queryset=Product.objects.all())
    amount = forms.IntegerField(min_value=1)

pastry_shop/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

pastry_shop/blog/views.py
from typing import Any, Dict, Type, Optional

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import QuerySet
from django.forms.forms import BaseForm
from django.forms.models import BaseModelForm
from django.http.response import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls.base import reverse_lazy, reverse
from django.views.generic.base import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormMixin
from django.views.generic.list import ListView

from pastry_shop.blog.forms import PostForm, CommentForm
from pastry_shop.blog.models import Post, Comment
from pastry_shop.users.models import User


class MainPageView(View):
    def get(self, request):
        recent_posts = Post.objects.order_by("-created")[:3]
        return render(request, "pages/home.html", {"recent_posts": recent_posts})


class PostListView(ListView):
    model = Post
    template_name = "blog/post_list.html"
    context_object_name = "posts"
    paginate_by = 3

    def get_queryset(self) -> QuerySet:
        return Post.objects.order_by("-created")


class PostDetailView(FormMixin, DetailView):
    model = Post
    template_name = "blog/post_detail.html"
    form_class = CommentForm

    def get_success_url(self) -> str:
        return reverse("blog:post-detail", kwargs={"pk": self.object.pk})

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context["form"] = CommentForm()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form: BaseForm) -> HttpResponse:
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.post = self.object
        comment.save()
        return redirect(self.get_success_url())


class PostCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = "blog.add_post"
    model = Post
    template_name = "blog/post_form.html"
    form_class = PostForm

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        return redirect(self.get_success_url())

    def get_success_url(self) -> str:
        return reverse("blog:post-list")


class PostEditView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = "blog.change_post"
    model = Post
    template_name = "blog/post_form.html"
    form_class = PostForm

    def get_success_url(self) -> str:
        return reverse("blog:post-detail", kwargs={"pk": self.object.pk})


class PostDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = "blog.delete_post"
    model = Post
    template_name = "blog/post_confirm_delete.html"

    def get_success_url(self) -> str:
        return reverse("blog:post-list")


class CommentEditView(LoginRequiredMixin, UpdateView):
    model = Comment
    template_name = "blog/comment_form.html"
    form_class = CommentForm

    def get_success_url(self) -> str:
        return reverse("blog:post-detail", kwargs={"pk": self.object.post.pk})


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = "blog/comment_confirm_delete.html"

    def get_success_url(self) -> str:
        return reverse("blog:post-detail", kwargs={"pk": self.object.post.pk})

pastry_shop/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

pastry_shop/templates/shop/cart_detail.html
{% extends "base.html" %}

{% block title %}Cart{% endblock title %}

{% block content %}
<div class="table-responsive text-white">
{% if cart.products.all %}
<table class="table text-white">
  <thead class="table-dark">
  <tr>
    <th scope="col">Product name</th>
    <th scope="col">Amount</th>
    <th scope="col">Price</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  {% for el in cart.productcart_set.all %}
  <tr>
  <td><a href="{% url 'shop:product-detail' el.product.pk %}">{{ el.product.name }}</a></td>
  <td>{{ el.amount }}</td>
  <td>{{ el.get_price }}</td>
  <td class="text-center">
    <a class="btn btn-sm btn-outline-danger" href="{% url 'shop:cart-product-delete' el.product.pk %}">X</a></td>
  </tr>
  {% endfor %}
  <tr>
    <td></td>
    <td></td>
    <td>{{ cart.get_total }}</td>
    <td class="text-center">Total</td>
  </tr>
  </tbody>
</table>
  <div>
    <form action="" method="post">
      {% csrf_token %}
      <button class="btn btn-outline-success">Order</button>
    </form>
  </div>
  {% else %}
  <h4>No products in cart yet</h4>
{% endif %}
</div>
{% endblock content %}

pastry_shop/templates/shop/cart_product_confirm_delete.html
{% extends "base.html" %}

{% block title %}Remove from cart "{{ product.name }}"{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-md-12 d-flex justify-content-center text-white align-items-center mt-5 pt-5">
      <form action="" method="post" class="text-center">
      {% csrf_token %}
      <h3>Do you really want to remove this product from cart "{{ product.name }}" ?</h3>
      <button class="btn btn-outline-danger">Remove</button>
      </form>
    </div>
  </div>
{% endblock content %}

pastry_shop/templates/shop/category_confirm_delete.html
{% extends "base.html" %}

{% block title %}Delete "{{ category }}" category{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-md-12 d-flex justify-content-center text-white align-items-center mt-5 pt-5">
      <form action="" method="post" class="text-center">
      {% csrf_token %}
      <h3>Do you really want to delete this category "{{ category }}" ?</h3>
      <button class="btn btn-outline-danger">Delete</button>
      </form>
    </div>
  </div>
{% endblock content %}

pastry_shop/templates/shop/category_detail.html
{% extends "base.html" %}

{% block title %}Category {{ category.name }} products{% endblock title %}

{% block content %}
<div class="text-white row">
<div class="col-md-8">
<h3>Products:</h3>
<ul style="list-style: none">
  {% for product in category.product_set.all %}
    <li><a href="{% url "shop:product-detail" product.pk %}">{{ product.name }}</a></li>
  {% endfor %}
</ul>
</div>
<div class="col-md-4">
  {% if request.user.is_staff %}
    <a class="btn btn-outline-primary" href="{% url "shop:category-edit" category.slug %}">Edit</a>
    <a class="btn btn-outline-danger" href="{% url "shop:category-delete" category.slug %}">Delete</a>
  {% endif %}
  <a class="btn btn-outline-info" href="{% url "shop:category-list" %}">All categories</a>
</div>
</div>
{% endblock content %}

pastry_shop/templates/shop/category_list.html
{% extends "base.html" %}

{% block title %}Categories{% endblock title %}

{% block content %}
  <div class="text-white row">
  <div class="col-md-10">
  <h4>Categories:</h4>
  <ul style="list-style: none">
    {% for category in categories %}
      <li><a href="{% url "shop:category-detail" category.slug %}">{{ category.name }}</a></li>
    {% endfor %}
  </ul>
  </div>
  <div class="col-md-2">
    {% if request.user.is_staff %}
      <a class="btn btn-outline-success" href="{% url 'shop:category-create' %}">Add Category</a>
    {% endif %}
  </div>
  </div>
{% endblock content %}

pastry_shop/templates/shop/order_detail.html
{% extends "base.html" %}

{% block title %}Order {{ order.pk }}{% endblock title %}

{% block content %}
<div class="table-responsive text-white">
{% if order.products.all %}
<table class="table text-white">
  <thead class="table-dark">
  <tr>
    <th>Product name</th>
    <th>Amount</th>
    <th>Price</th>
  </tr>
  </thead>
  <tbody>
  {% for el in order.productorder_set.all %}
  <tr>
  <td><a href="{% url 'shop:product-detail' el.product.pk %}">{{ el.product.name }}</a></td>
  <td>{{ el.amount }}</td>
  <td>{{ el.get_price }}</td>
  </tr>
  {% endfor %}
  <tr>
    <td></td>
    <td>Total</td>
    <td>{{ order.get_total }}</td>
  </tr>
  </tbody>
</table>
{% else %}
<h4>No products in your order, error must have occurred</h4>
{% endif %}
</div>
{% endblock content %}

pastry_shop/templates/shop/order_list.html
{% extends "base.html" %}

{% block title %}Orders{% endblock title %}

{% block content %}
<div class="table-responsive text-white">
{% if orders %}
<h2>Orders</h2>
  <table class="table text-white">
  <thead class="table-dark">
  <tr>
    <th>Order id</th>
    <th>Order price</th>
    <th>Order status</th>
    <th>Order date</th>
  </tr>
  </thead>
  <tbody>
  {% for order in orders %}
    <tr>
    <td><a href="{% url 'shop:order-detail' order.pk %}">{{ order.pk }}</a></td>
    <td>{{ order.get_total }}</td>
    <td>{{ order.get_status_display }}</td>
    <td>{{ order.created }}</td>
    </tr>
  {% endfor %}
  </tbody>
  </table>
{% else %}
<h2>You haven't made any orders yet</h2>
{% endif %}
</div>
{% endblock content %}

pastry_shop/templates/shop/product_confirm_delete.html
{% extends "base.html" %}

{% block title %}Delete "{{ product }}" product{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-md-12 d-flex justify-content-center text-white align-items-center mt-5 pt-5">
      <form action="" method="post" class="text-center">
      {% csrf_token %}
      <h3>Do you really want to delete this product "{{ product }}" ?</h3>
      <button class="btn btn-outline-danger">Delete</button>
      </form>
    </div>
  </div>
{% endblock content %}

pastry_shop/templates/shop/product_detail.html
{% extends "base.html" %}

{% block title %}Product {{ product.name }}{% endblock title %}

{% block content %}
  <div class="row text-white">
    <div class="col-md-8">
      <h2>{{ product.name }}</h2>
      <p>{{ product.description }}</p>
      <p>Price: {{ product.price }}</p>
    </div>
    {% if request.user.is_staff %}
      <div class="col-md-4 d-flex justify-content-end align-items-center">
        <a class="btn btn-outline-primary" href="{% url "shop:product-edit" product.pk %}">Edit</a>
        <a class="btn btn-outline-danger ml-2" href="{% url "shop:product-delete" product.pk %}">Delete</a>
      </div>
    {% endif %}
  </div>
  <div class="row">
      <div class="col-md-12 d-flex text-white">
      <h4>Available in</h4>
      <ul style="list-style: none" class="d-flex justify-content-end">
      {% for shop in product.shop_set.all %}
        <li class="mt-1"><a href="{% url "shop:shop-detail" shop.pk %}">{{ shop }}</a>&nbsp;</li>
      {% endfor %}
      </ul>
    </div>
  </div>
  <div class="row">
  {% if request.user.is_authenticated %}
    <div class="col-md-4">
      <form action="" method="post">
        {% csrf_token %}
        <button class="btn btn-outline-success">Add to cart</button>
        {{ form.amount }}
      </form>
    </div>
  {% endif %}
    <div class="col-md-6 d-flex text-white">
    <h4 class="mt-1">Categories:</h4>
      <ul style="list-style: none" class="d-flex justify-content-end">
      {% for category in product.categories.all %}
        <li class="mt-2"><a href="{% url "shop:category-detail" category.slug %}">{{ category.name }}</a>&nbsp;</li>
      {% endfor %}
      </ul>
    </div>
    <div class="col-md-2 d-flex justify-content-end align-items-center">
      <a class="btn btn-outline-info mb-2" href="{% url 'shop:category-list' %}">All categories</a>
    </div>
  </div>

{% endblock content %}

pastry_shop/templates/shop/shop_confirm_delete.html
{% extends "base.html" %}

{% block title %}Delete shop "{{ shop }}"{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-md-12 d-flex justify-content-center text-white align-items-center mt-5 pt-5">
      <form action="" method="post" class="text-center">
      {% csrf_token %}
      <h3>Do you really want to delete this shop "{{ shop }}" ?</h3>
      <button class="btn btn-outline-danger">Delete</button>
      </form>
    </div>
  </div>
{% endblock content %}

pastry_shop/templates/shop/shop_detail.html
{% extends "base.html" %}

{% block title %}Location details{% endblock title %}

{% block content %}
<div class="text-white">
<div class="row">
<div class="col-md-8">
  <h3>{{ shop.name }}</h3>
  <p>
    City: {{ shop.city }}<br>
    Street: {{ shop.street }}
  </p>
</div>
{% if request.user.is_staff %}
<div class="col-md-4 d-flex justify-content-end align-items-center">
  <a class="btn btn-outline-primary" href="{% url "shop:shop-edit" shop.pk %}">Edit</a>
  <a class="btn btn-outline-danger ml-2" href="{% url "shop:shop-delete" shop.pk %}">Delete</a>
  <a class="btn btn-outline-success ml-2" href="{% url 'shop:shop-product-add' shop.pk %}">Add product</a>
</div>
{% endif %}
</div>
<div class="row">
<div class="col-md-8">
  {% if shop.products.all %}
    <h4>Products:</h4>
    <ul style="list-style: none">
    {% for el in shop.availability_set.all %}
      <li class="d-flex">
      <p>
        <a href="{% url 'shop:product-detail' el.product.pk %}">{{ el.product.name }}</a><br>
      In stock: {{ el.amount }}
      </p>
      {% if request.user.is_staff %}
        <div class="d-flex justify-content-center align-items-start">
          <a class="btn btn-outline-danger btn-sm ml-2"
           href="{% url 'shop:shop-product-remove' shop.pk el.product.pk %}">Remove
          </a>
        </div>
      {% endif %}
      </li>
    {% endfor %}
    </ul>
  {% endif %}
</div>
</div>
</div>
{% endblock content %}

pastry_shop/templates/shop/shop_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}{% if action == "create" %}
Create
  {% else %}
  Edit
{% endif %} Shop{% endblock title %}

{% block content %}
  <div class="text-white">
  <form action="" method="post">
  {% csrf_token %}
  {{ form|crispy }}
  {% if action == "create" %}
  <button class="btn btn-outline-success">Create</button>
    {% else %}
    <button class="btn btn-outline-primary">Edit</button>
  {% endif %}
  </form>
  </div>
{% endblock content %}

pastry_shop/templates/shop/shop_product_add_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Add product to shop{% endblock title %}

{% block content %}
  <div class="text-white">
  <form action="" method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-outline-success">Add</button>
  </form>
  </div>
{% endblock content %}

pastry_shop/templates/shop/shop_product_confirm_delete.html
{% extends "base.html" %}

{% block title %}Remove {{ product.product.name }} from this shop {{ shop.name }} ?{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-md-12 d-flex justify-content-center text-white align-items-center mt-5 pt-5">
      <form action="" method="post" class="text-center">
      {% csrf_token %}
      <h3>Do you really want to remove this product "{{ product.product.name }}" from this shop ?</h3>
      <button class="btn btn-outline-danger">Remove</button>
      </form>
    </div>
  </div>
{% endblock content %}