config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

from pastry_shop.blog.views import MainPageView

urlpatterns = [
    path("", MainPageView.as_view(), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("pastry_shop.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("blog/", include("pastry_shop.blog.urls", namespace="blog")),
    path("shop/", include("pastry_shop.shop.urls", namespace="shop")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

pastry_shop/blog/urls.py
from django.urls import path

from pastry_shop.blog.views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostEditView,
    PostDeleteView,
    CommentEditView,
    CommentDeleteView,
)

app_name = "blog"

urlpatterns = [
    path("posts/", PostListView.as_view(), name="post-list"),
    path("posts/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("posts/add/", PostCreateView.as_view(), name="post-create"),
    path("posts/<int:pk>/edit/", PostEditView.as_view(), name="post-edit"),
    path("posts/<int:pk>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path("comments/<int:pk>/edit/", CommentEditView.as_view(), name="comment-edit"),
    path(
        "comments/<int:pk>/delete/", CommentDeleteView.as_view(), name="comment-delete"
    ),
]

pastry_shop/shop/urls.py
from django.urls import path

from pastry_shop.shop.views import (
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductEditView,
    ProductDeleteView,
    CategoryListView,
    CategoryDetailView,
    CategoryCreateView,
    CategoryEditView,
    CategoryDeleteView,
    ShopListView,
    ShopDetailView,
    ShopCreateView,
    ShopEditView,
    ShopDeleteView,
    CartDetailView,
    CartProductDeleteView,
    OrderListView,
    OrderDetailView,
    ShopProductAddView,
    ShopProductDeleteView,
)

app_name = "shop"

urlpatterns = [
    path("products/", ProductListView.as_view(), name="product-list"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product-detail"),
    path("products/add/", ProductCreateView.as_view(), name="product-create"),
    path("products/<int:pk>/edit/", ProductEditView.as_view(), name="product-edit"),
    path(
        "products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product-delete"
    ),
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path(
        "category/<slug:slug>/products",
        CategoryDetailView.as_view(),
        name="category-detail",
    ),
    path("category/add", CategoryCreateView.as_view(), name="category-create"),
    path("category/<slug:slug>/edit", CategoryEditView.as_view(), name="category-edit"),
    path(
        "category/<slug:slug>/delete",
        CategoryDeleteView.as_view(),
        name="category-delete",
    ),
    path("shops/", ShopListView.as_view(), name="shop-list"),
    path("shop/<int:pk>/", ShopDetailView.as_view(), name="shop-detail"),
    path("shop/add/", ShopCreateView.as_view(), name="shop-create"),
    path("shop/<int:pk>/edit/", ShopEditView.as_view(), name="shop-edit"),
    path("shop/<int:pk>/delete/", ShopDeleteView.as_view(), name="shop-delete"),
    path(
        "shop/<int:pk>/product/add/",
        ShopProductAddView.as_view(),
        name="shop-product-add",
    ),
    path(
        "shop/<int:pk>/product/<int:product_id>/",
        ShopProductDeleteView.as_view(),
        name="shop-product-remove",
    ),
    path("cart/", CartDetailView.as_view(), name="cart-detail"),
    path(
        "cart/product/<int:pk>/delete/",
        CartProductDeleteView.as_view(),
        name="cart-product-delete",
    ),
    path("orders/", OrderListView.as_view(), name="order-list"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
]

pastry_shop/users/urls.py
from django.urls import path

from pastry_shop.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

pastry_shop/blog/models.py
from django.db import models

# Create your models here.
from django.utils.translation import gettext_lazy as _

from pastry_shop.users.models import User


class Post(models.Model):
    title = models.CharField(_("Title"), max_length=64)
    content = models.TextField(_("Content"))
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return self.title


class Comment(models.Model):
    content = models.TextField(_("Content"))
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    post = models.ForeignKey("Post", on_delete=models.CASCADE, related_name="comments")

    def __str__(self):
        return f"{self.content[:20]} - {self.author.username}"

pastry_shop/shop/models.py
from autoslug import AutoSlugField
from django.db import models

# Create your models here.
from django.utils.translation import gettext_lazy as _

from pastry_shop.users.models import User


class Category(models.Model):
    name = models.CharField(_("Name"), max_length=100)
    slug = AutoSlugField(populate_from="name", unique=True, always_update=True)

    class Meta:
        verbose_name_plural = "Categories"
        ordering = ("name",)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(_("Name"), max_length=100)
    description = models.TextField(_("Description"))
    price = models.DecimalField(_("Price"), max_digits=7, decimal_places=2)
    amount = models.IntegerField(_("Amount"))
    categories = models.ManyToManyField(Category)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


class Cart(models.Model):
    client = models.OneToOneField(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through="ProductCart")

    def get_total(self):
        total = 0
        for product in self.productcart_set.all():
            total += product.get_price()
        return total

    def __str__(self):
        return f"{self.client.username}'s cart({self.pk})"


class ProductCart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    amount = models.IntegerField()

    def get_price(self):
        return self.amount * self.product.price


class Order(models.Model):
    class Status(models.IntegerChoices):
        PENDING = 1, _("Pending")
        READY = 2, _("Ready for pickup")
        PAID = 3, _("Paid")
        DELIVERED = 4, _("Delivered")

    client = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through="ProductOrder")
    status = models.IntegerField(choices=Status.choices, default=Status.PENDING)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.client.username}'s order({self.pk})"

    def get_total(self):
        total = 0
        for product in self.productorder_set.all():
            total += product.get_price()
        return total


class ProductOrder(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    amount = models.IntegerField()

    def get_price(self):
        return self.amount * self.product.price


class Shop(models.Model):
    name = models.CharField(_("Name"), max_length=100)
    city = models.CharField(_("City"), max_length=100)
    street = models.CharField(_("Street"), max_length=100)
    products = models.ManyToManyField(Product, through="Availability")

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


class Availability(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    amount = models.IntegerField()

pastry_shop/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for Pastry Shop."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

pastry_shop/blog/forms.py
from django import forms

from pastry_shop.blog.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "content")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)

pastry_shop/shop/forms.py
from django import forms

from pastry_shop.shop.models import Product, ProductCart


class ProductForm(forms.ModelForm):
    amount = forms.IntegerField(min_value=1)
    price = forms.DecimalField(min_value=0.01, max_digits=7, decimal_places=2)

    class Meta:
        model = Product
        fields = "__all__"
        widgets = {"categories": forms.CheckboxSelectMultiple}


class CartProductAddForm(forms.Form):
    amount = forms.IntegerField(min_value=1)


class ShopProductAddForm(forms.Form):
    product = forms.ModelChoiceField(queryset=Product.objects.all())
    amount = forms.IntegerField(min_value=1)

pastry_shop/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

pastry_shop/blog/views.py
from typing import Any, Dict, Type, Optional

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import QuerySet
from django.forms.forms import BaseForm
from django.forms.models import BaseModelForm
from django.http.response import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls.base import reverse_lazy, reverse
from django.views.generic.base import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormMixin
from django.views.generic.list import ListView

from pastry_shop.blog.forms import PostForm, CommentForm
from pastry_shop.blog.models import Post, Comment
from pastry_shop.users.models import User


class MainPageView(View):
    def get(self, request):
        recent_posts = Post.objects.order_by("-created")[:3]
        return render(request, "pages/home.html", {"recent_posts": recent_posts})


class PostListView(ListView):
    model = Post
    template_name = "blog/post_list.html"
    context_object_name = "posts"
    paginate_by = 3

    def get_queryset(self) -> QuerySet:
        return Post.objects.order_by("-created")


class PostDetailView(FormMixin, DetailView):
    model = Post
    template_name = "blog/post_detail.html"
    form_class = CommentForm

    def get_success_url(self) -> str:
        return reverse("blog:post-detail", kwargs={"pk": self.object.pk})

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context["form"] = CommentForm()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form: BaseForm) -> HttpResponse:
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.post = self.object
        comment.save()
        return redirect(self.get_success_url())


class PostCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = "blog.add_post"
    model = Post
    template_name = "blog/post_form.html"
    form_class = PostForm

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        return redirect(self.get_success_url())

    def get_success_url(self) -> str:
        return reverse("blog:post-list")


class PostEditView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = "blog.change_post"
    model = Post
    template_name = "blog/post_form.html"
    form_class = PostForm

    def get_success_url(self) -> str:
        return reverse("blog:post-detail", kwargs={"pk": self.object.pk})


class PostDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = "blog.delete_post"
    model = Post
    template_name = "blog/post_confirm_delete.html"

    def get_success_url(self) -> str:
        return reverse("blog:post-list")


class CommentEditView(LoginRequiredMixin, UpdateView):
    model = Comment
    template_name = "blog/comment_form.html"
    form_class = CommentForm

    def get_success_url(self) -> str:
        return reverse("blog:post-detail", kwargs={"pk": self.object.post.pk})


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = "blog/comment_confirm_delete.html"

    def get_success_url(self) -> str:
        return reverse("blog:post-detail", kwargs={"pk": self.object.post.pk})

pastry_shop/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

pastry_shop/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Pastry Shop{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Pastry shop website to sell their goods and make blog posts about them.">
    <meta name="author" content="Maciej Purta">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}

    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">


    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}

      <!-- Bootstrap JS and its dependencies-->
      <script defer src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->

      <script defer src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}

  </head>

  <body class="d-flex flex-column min-vh-100">

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">Pastry Shop</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.path == '/' %}active{% endif %}">
              <a class="nav-link" href="{% url 'home' %}">{% trans "Home" %}</a>
            </li>
            <li class="nav-item {% if 'about' in request.path %}active{% endif %}">
              <a class="nav-link" href="{% url 'about' %}">{% trans "About" %}</a>
            </li>
            <li class="nav-item {% if 'post' in request.path %}active{% endif %}">
              <a class="nav-link" href="{% url 'blog:post-list' %}">{% trans "Posts" %}</a>
            </li>
            <li class="nav-item {% if 'product' in request.path %}active{% endif %}">
              <a class="nav-link" href="{% url 'shop:product-list' %}">{% trans "Products" %}</a>
            </li>
            <li class="nav-item {% if 'shop/shop' in request.path %}active{% endif %}">
              <a class="nav-link" href="{% url 'shop:shop-list' %}">{% trans "Locations" %}</a>
            </li>
          </ul>
          <ul class="navbar-nav mr-right">
            {% if request.user.is_authenticated %}
              <li class="nav-item {% if 'order' in request.path %}active{% endif %}">
                <a class="nav-link" href="{% url 'shop:order-list' %}">{% trans "Orders" %}</a>
              </li>
              <li class="nav-item {% if 'cart' in request.path %}active{% endif %}">
                <a class="nav-link" href="{% url 'shop:cart-detail' %}">{% trans "Cart" %}</a>
              </li>
              <li class="nav-item {% if request.user.username  in request.path %}active{% endif %}">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>
    <div class="container" style="padding-top: 7%; padding-bottom: 7%;">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
        <p>{{ request.path }}</p>
      {% endblock content %}
    </div> <!-- /container -->
    <footer class="text-center text-white mt-auto bg-dark">
      <!-- Grid container -->
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-4">
            <div class="container p-4">
              <div class="p-4">
                <h4>Reach us on</h4>
                <ol class="list-unstyled">
                  <li><a href="#">Instagram</a></li>
                  <li><a href="#">Twitter</a></li>
                  <li><a href="#">Facebook</a></li>
                </ol>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="container p-4">
              <div class="p-4">
                <h4>Contact Info</h4>
                <ol class="list-unstyled">
                  <li>Phone: 123 456 789</li>
                  <li>Email: pastry.shop@pastry.com</li>
                </ol>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="container p-4">
              <div class="p-4">
                <h4>Navigation</h4>
                <ol class="list-unstyled">
                  <li><a href="{% url 'home' %}">Home</a></li>
                  <li><a href="{% url 'about' %}">About</a></li>
                  <li><a href="{% url 'blog:post-list' %}">Posts</a></li>
                  <li><a href="{% url 'shop:product-list' %}">Products</a></li>
                  <li><a href="{% url 'shop:shop-list' %}">Locations</a></li>
                </ol>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Grid container -->

      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: #191a1c;">
        © 2021 Maciej Purta:
        <a class="text-white" href="https://www.github.com/raekker">Github</a>
      </div>
      <!-- Copyright -->
    </footer>

    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    {# Script tags with only code, no src (defer by default) #}
    {% endblock inline_javascript %}
  </body>
</html>